### ISSUE TITLE
improvements

### ISSUE THREAD

**Issue by mobyvb** [mobyvb/tasklist#1]
* save task list to file on shutdown
* if task list file exists on startup, load it before first prompt
* truncate duration to a precision of time.Second
* add optional argument to "work" command allowing user to specify a predefined countdown time. If this argument is provided, the timer will count down instead of up. Once 0 is reached, go back to the beginning of the REPL loop
* add some comments explaining what the code does

---

Files: main.go

**Comment by black-crowned-night-heron** [comment]
working on it

**Comment by black-crowned-night-heron** [comment]
working on it

**Comment by black-crowned-night-heron** [comment]
working on it
